# Copyright (c) 2024, 2026, Oracle and/or its affiliates. All rights reserved.
# The Universal Permissive License (UPL), Version 1.0 as shown at https://oss.oracle.com/licenses/upl/
apiVersion: kyverno.io/v1
kind: ClusterPolicy 
metadata:
  name: add-labels 
spec:
  rules:
  - name: add-team 
    match:
      any:
      - resources:
          kinds:
          - Deployment
    mutate:
      patchStrategicMerge:
        metadata: 
          labels:
            +(team) : bravo